############################
#  Red Studio Development  #
#      by: Nikonbite       #
############################

PREFIX:               "§c§lLobby §7:: §f"

COMMON:
  NO_PERMS:           "У вас нет прав для выполнения этой команды!"

PAD:

  # Jump Pad привязан к блоку слизи,
  # и изменить его не получится.
  # В дальнейших обновлениях я это добавлю

  MULTIPLIER_X: 3.5
  MULTIPLIER_Y: 0.8

JOIN_MESSAGES:
  DEFAULT:            "§e▸ §fИгрок §e%s§f зашёл на проект! §e◂"
  MOTD:
    - "§c§lExample Network"
    - ""
    - "§fТут что-то можно написать, но я не придумал."

COMMANDS:
  GMS_SUCCESS:        "Ваш текущий режим игры: §aВыживание§f."
  GMC_SUCCESS:        "Ваш текущий режим игры: §dКреатив§f."
  GMA_SUCCESS:        "Ваш текущий режим игры: §eПриключение§f."
  GMSP_SUCCESS:       "Ваш текущий режим игры: §7Наблюдатель§f."
  FLY_SUCCESS:        "Вы установили режим полёта на: "
  GM_ALREADY:         "У вас уже установлен этот режим игры!"
  CORE_RELOADED:      "Конфиг успешно перезагружен!"
  CORE_HELP:
    - "§7§m============================================="
    - "§7"
    - "§fСписок команд для §c/redlobby§f:"
    - " §8- §c/redlobby reload §7▸ §fПерезагрузить конфиг"
    - "§7"
    - "§7§m============================================="